### ISSUE TITLE
Will not start - Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by grokit2** [TypeTalk/TypeTalk#1]
Installed .deb package, did not start. Output from console:
grokit@pc:~$ /opt/typetalk/typetalk.sh
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/typetalk/Application : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

I have java-common installed as well as icedtea. Have no problem with any other java code including minecraft, Aptana Studio, and browser java apps. All dependencies were satisfied before install.

My machine:
OS: Ubuntu 14.04 trusty
Kernel: x86_64 Linux 3.13.0-78-generic
DE: KDE 4.14.13
WM: KWin
CPU: Intel Core i7-6700K CPU @ 4.001GHz
GPU: GeForce GTX 980 Ti
RAM: 4129MB / 32124MB

More information upon request.
-Alan

**Comment by grokit2** [comment]
Uploaded verbose console output
[TypeTalk_bug.txt](https://github.com/TypeTalk/TypeTalk/files/147545/TypeTalk_bug.txt)

**Comment by raginggoblin** [comment]
Hi Grokit2,
Congratulations, you opened up the first bug report! Having a few bugs around gives me the feeling we are doing serious business. No kidding, from your logs I see you installed java 7. But TypeTalk requires java 8. This is a requirement in the rpm but apparently this is not properly configured in the deb. You can install version 8 with 'sudo apt-get install openjdk-8-jre' I will look for better ways than alien to compose a deb package.

**Comment by raginggoblin** [comment]
I released v1.2 creating deb packages now with jdeb. This should install the proper java version through dependency management.

**Comment by grokit2** [comment]
Cool. Is it up on the the website to download yet? I'll try it as soon as it is.

-Alan

**Comment by raginggoblin** [comment]
Yes, updated the download links/buttons.

**Comment by grokit2** [comment]
Definitely fixed the dependencies thing. 
But java 8 is not in the regular repositories for Kubuntu 14.04 LTS.   Installing via PPA . . .

**Comment by raginggoblin** [comment]
Nice to hear, java 8 has a lot of improvements for developers. That is the reason I use it. Thanks for trying this out.

**Comment by grokit2** [comment]
Just an FYI, I haven't been able to get it working on Kubuntu 14.04. I haven't solved the java 8 dependencies with a PPA. No worries though because it starts in my test distro (kubuntu 15.10).  Looks good but I really didn't use it too much yet.
Since I'm going to be upgrading to the 16.04 release in a month and a half I'm not going to bother submitting a bug.  This will still affect all users of the 14.04 LTS release because Ubuntu isn't backporting java 8.

Alan
